/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class adminwelcomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form adminwelcomeGUI
     */
    public adminwelcomeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        Employees = new javax.swing.JButton();
        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        NoOfVacantRooms = new javax.swing.JTextField();
        NoOfUnpaidChallans = new javax.swing.JTextField();
        admwelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterButton.setBorder(null);
        RegisterButton.setContentAreaFilled(false);
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(20, 90, 140, 30);

        EditButton.setBorder(null);
        EditButton.setContentAreaFilled(false);
        getContentPane().add(EditButton);
        EditButton.setBounds(20, 140, 140, 30);

        RoomsButton.setBorder(null);
        RoomsButton.setContentAreaFilled(false);
        getContentPane().add(RoomsButton);
        RoomsButton.setBounds(20, 190, 140, 30);

        Employees.setBorder(null);
        Employees.setContentAreaFilled(false);
        getContentPane().add(Employees);
        Employees.setBounds(20, 230, 140, 30);

        VoucherButton.setBorder(null);
        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        getContentPane().add(VoucherButton);
        VoucherButton.setBounds(30, 280, 130, 29);

        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(20, 510, 130, 30);

        NoOfVacantRooms.setBorder(null);
        NoOfVacantRooms.setOpaque(false);
        getContentPane().add(NoOfVacantRooms);
        NoOfVacantRooms.setBounds(610, 246, 0, 40);

        NoOfUnpaidChallans.setBorder(null);
        NoOfUnpaidChallans.setOpaque(false);
        getContentPane().add(NoOfUnpaidChallans);
        NoOfUnpaidChallans.setBounds(610, 310, 0, 40);

        admwelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adm_welcome.jpg"))); // NOI18N
        getContentPane().add(admwelcome);
        admwelcome.setBounds(0, 0, 800, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminwelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminwelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminwelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminwelcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminwelcomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JButton Employees;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField NoOfUnpaidChallans;
    private javax.swing.JTextField NoOfVacantRooms;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JButton VoucherButton;
    private javax.swing.JLabel admwelcome;
    // End of variables declaration//GEN-END:variables
}
