/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class adminvoucherGUI extends javax.swing.JFrame {

    /**
     * Creates new form adminvoucherGUI
     */
    public adminvoucherGUI() {
        initComponents();
        setSize(810,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        Employees = new javax.swing.JButton();
        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ViewChallanButton = new javax.swing.JButton();
        CheckButton = new javax.swing.JButton();
        PayChallanButton = new javax.swing.JButton();
        UnpaidChallansTF = new javax.swing.JTextField();
        VoucherNoTF = new javax.swing.JTextField();
        VoucherNo2TF = new javax.swing.JTextField();
        admvoucher = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterButton.setBorder(null);
        RegisterButton.setContentAreaFilled(false);
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(20, 90, 140, 30);

        EditButton.setBorder(null);
        EditButton.setContentAreaFilled(false);
        getContentPane().add(EditButton);
        EditButton.setBounds(20, 140, 140, 30);

        RoomsButton.setBorder(null);
        RoomsButton.setContentAreaFilled(false);
        getContentPane().add(RoomsButton);
        RoomsButton.setBounds(20, 190, 140, 30);

        Employees.setBorder(null);
        Employees.setContentAreaFilled(false);
        getContentPane().add(Employees);
        Employees.setBounds(20, 230, 140, 30);

        VoucherButton.setBorder(null);
        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        getContentPane().add(VoucherButton);
        VoucherButton.setBounds(30, 280, 130, 29);

        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(20, 510, 130, 30);

        ViewChallanButton.setBorder(null);
        ViewChallanButton.setContentAreaFilled(false);
        getContentPane().add(ViewChallanButton);
        ViewChallanButton.setBounds(580, 189, 170, 40);

        CheckButton.setBorder(null);
        CheckButton.setContentAreaFilled(false);
        getContentPane().add(CheckButton);
        CheckButton.setBounds(580, 330, 170, 30);

        PayChallanButton.setBorder(null);
        PayChallanButton.setContentAreaFilled(false);
        PayChallanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayChallanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PayChallanButton);
        PayChallanButton.setBounds(580, 460, 180, 30);

        UnpaidChallansTF.setBorder(null);
        UnpaidChallansTF.setOpaque(false);
        getContentPane().add(UnpaidChallansTF);
        UnpaidChallansTF.setBounds(450, 200, 84, 26);

        VoucherNoTF.setBorder(null);
        VoucherNoTF.setOpaque(false);
        getContentPane().add(VoucherNoTF);
        VoucherNoTF.setBounds(220, 340, 320, 20);

        VoucherNo2TF.setBorder(null);
        VoucherNo2TF.setOpaque(false);
        getContentPane().add(VoucherNo2TF);
        VoucherNo2TF.setBounds(220, 470, 320, 20);

        admvoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin_voucher.jpg"))); // NOI18N
        getContentPane().add(admvoucher);
        admvoucher.setBounds(0, 0, 800, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayChallanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayChallanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayChallanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminvoucherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminvoucherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminvoucherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminvoucherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminvoucherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton Employees;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton PayChallanButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JTextField UnpaidChallansTF;
    private javax.swing.JButton ViewChallanButton;
    private javax.swing.JButton VoucherButton;
    private javax.swing.JTextField VoucherNo2TF;
    private javax.swing.JTextField VoucherNoTF;
    private javax.swing.JLabel admvoucher;
    // End of variables declaration//GEN-END:variables
}
