/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class adminregisterGUI extends javax.swing.JFrame {

    /**
     * Creates new form adminregisterGUI
     */
    public adminregisterGUI() {
        initComponents();
        setResizable(false);
        setSize(810,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        Employees = new javax.swing.JButton();
        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        Register2Button = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        AdminRadioButton = new javax.swing.JRadioButton();
        NameTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        SalaryTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        CNICTF = new javax.swing.JTextField();
        DepartmentIDTF = new javax.swing.JTextField();
        PhineTF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterButton.setBorder(null);
        RegisterButton.setContentAreaFilled(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(20, 90, 140, 30);

        EditButton.setBorder(null);
        EditButton.setContentAreaFilled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton);
        EditButton.setBounds(20, 140, 140, 30);

        RoomsButton.setBorder(null);
        RoomsButton.setContentAreaFilled(false);
        RoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RoomsButton);
        RoomsButton.setBounds(20, 190, 140, 30);

        Employees.setBorder(null);
        Employees.setContentAreaFilled(false);
        Employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(Employees);
        Employees.setBounds(20, 230, 140, 30);

        VoucherButton.setBorder(null);
        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        VoucherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoucherButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VoucherButton);
        VoucherButton.setBounds(30, 280, 130, 29);

        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(20, 510, 130, 30);

        Register2Button.setBorder(null);
        Register2Button.setContentAreaFilled(false);
        Register2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register2ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Register2Button);
        Register2Button.setBounds(340, 490, 140, 29);

        CancelButton.setBorder(null);
        CancelButton.setContentAreaFilled(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(500, 490, 150, 29);

        AdminRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        AdminRadioButton.setBorder(null);
        AdminRadioButton.setOpaque(false);
        getContentPane().add(AdminRadioButton);
        AdminRadioButton.setBounds(460, 410, 30, 20);

        NameTF.setBorder(null);
        NameTF.setOpaque(false);
        getContentPane().add(NameTF);
        NameTF.setBounds(220, 256, 260, 10);

        EmailTF.setBorder(null);
        EmailTF.setOpaque(false);
        getContentPane().add(EmailTF);
        EmailTF.setBounds(220, 306, 260, 14);

        SalaryTF.setBorder(null);
        SalaryTF.setOpaque(false);
        getContentPane().add(SalaryTF);
        SalaryTF.setBounds(220, 360, 250, 20);

        PhoneTF.setBorder(null);
        PhoneTF.setOpaque(false);
        PhoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneTFActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneTF);
        PhoneTF.setBounds(510, 250, 250, 14);

        CNICTF.setBorder(null);
        CNICTF.setOpaque(false);
        getContentPane().add(CNICTF);
        CNICTF.setBounds(510, 306, 250, 14);

        DepartmentIDTF.setBorder(null);
        DepartmentIDTF.setOpaque(false);
        DepartmentIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentIDTFActionPerformed(evt);
            }
        });
        getContentPane().add(DepartmentIDTF);
        DepartmentIDTF.setBounds(510, 360, 250, 20);

        PhineTF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin_registeremp.jpg"))); // NOI18N
        getContentPane().add(PhineTF);
        PhineTF.setBounds(0, 0, 800, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Register2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register2ButtonActionPerformed
       setVisible(false);
        adminwelcomeGUI a = new adminwelcomeGUI();
        a.setVisible(true);
    }//GEN-LAST:event_Register2ButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        adminwelcomeGUI a = new adminwelcomeGUI();
        a.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void PhoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneTFActionPerformed

    private void DepartmentIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentIDTFActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
       setVisible(false);
        adminrg1GUI a = new adminrg1GUI();
        a.setVisible(true);
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
         setVisible(false);
        adminedit1GUI a = new adminedit1GUI();
        a.setVisible(true);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void RoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsButtonActionPerformed
        setVisible(false);
        adminroomsGUI a = new adminroomsGUI();
        a.setVisible(true);
    }//GEN-LAST:event_RoomsButtonActionPerformed

    private void EmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeesActionPerformed
         setVisible(false);
        admitempGUI a = new admitempGUI();
        a.setVisible(true);
    }//GEN-LAST:event_EmployeesActionPerformed

    private void VoucherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoucherButtonActionPerformed
        setVisible(false);
        adminvoucherGUI a = new adminvoucherGUI();
        a.setVisible(true);
    }//GEN-LAST:event_VoucherButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        setVisible(false);
        IntialGui a = new IntialGui();
        a.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminregisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminregisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminregisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminregisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminregisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminRadioButton;
    private javax.swing.JTextField CNICTF;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DepartmentIDTF;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JButton Employees;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel PhineTF;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JButton Register2Button;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JTextField SalaryTF;
    private javax.swing.JButton VoucherButton;
    // End of variables declaration//GEN-END:variables
}
