/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class admreg3GUI extends javax.swing.JFrame {

    /**
     * Creates new form admreg3
     */
    public admreg3GUI() {
        initComponents();
        setSize(810,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        Employees = new javax.swing.JButton();
        FirstNameTF = new javax.swing.JTextField();
        StudentIDTF = new javax.swing.JTextField();
        FatherNameTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        DateOfBirthTF = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        RoomTF = new javax.swing.JTextField();
        FacilitiesTF = new javax.swing.JTextField();
        LastNameTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        ProgramTF = new javax.swing.JTextField();
        CNICTF = new javax.swing.JTextField();
        BuildingTF = new javax.swing.JTextField();
        NextButton = new javax.swing.JButton();
        Register2Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VoucherButton.setBorder(null);
        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        getContentPane().add(VoucherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 29));

        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 130, 30));

        RegisterButton.setBorder(null);
        RegisterButton.setContentAreaFilled(false);
        getContentPane().add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        EditButton.setBorder(null);
        EditButton.setContentAreaFilled(false);
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 30));

        RoomsButton.setBorder(null);
        RoomsButton.setContentAreaFilled(false);
        getContentPane().add(RoomsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 30));

        Employees.setBorder(null);
        Employees.setContentAreaFilled(false);
        getContentPane().add(Employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        FirstNameTF.setBorder(null);
        FirstNameTF.setOpaque(false);
        getContentPane().add(FirstNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 170, 20));

        StudentIDTF.setBorder(null);
        StudentIDTF.setOpaque(false);
        getContentPane().add(StudentIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 460, -1));

        FatherNameTF.setBorder(null);
        FatherNameTF.setOpaque(false);
        getContentPane().add(FatherNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 160, -1));

        PhoneTF.setBorder(null);
        PhoneTF.setOpaque(false);
        getContentPane().add(PhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 160, 10));

        DateOfBirthTF.setBorder(null);
        DateOfBirthTF.setOpaque(false);
        getContentPane().add(DateOfBirthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 160, -1));

        AddressTF.setBorder(null);
        AddressTF.setOpaque(false);
        getContentPane().add(AddressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 440, 10));

        RoomTF.setBorder(null);
        RoomTF.setOpaque(false);
        getContentPane().add(RoomTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 180, 10));

        FacilitiesTF.setBorder(null);
        FacilitiesTF.setOpaque(false);
        getContentPane().add(FacilitiesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 430, -1));

        LastNameTF.setBorder(null);
        LastNameTF.setOpaque(false);
        getContentPane().add(LastNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 180, -1));

        EmailTF.setBorder(null);
        EmailTF.setOpaque(false);
        getContentPane().add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 180, 10));

        ProgramTF.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ProgramTF.setBorder(null);
        ProgramTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramTFActionPerformed(evt);
            }
        });
        getContentPane().add(ProgramTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 190, 20));

        CNICTF.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CNICTF.setBorder(null);
        CNICTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNICTFActionPerformed(evt);
            }
        });
        getContentPane().add(CNICTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 170, 20));

        BuildingTF.setBorder(null);
        BuildingTF.setOpaque(false);
        getContentPane().add(BuildingTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 180, -1));

        NextButton.setBorder(null);
        NextButton.setBorderPainted(false);
        NextButton.setContentAreaFilled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 140, 30));

        Register2Button.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Register2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amdin_registernew3.jpg"))); // NOI18N
        Register2Button.setOpaque(true);
        getContentPane().add(Register2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextButtonActionPerformed

    private void CNICTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNICTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNICTFActionPerformed

    private void ProgramTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admreg3GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTF;
    private javax.swing.JTextField BuildingTF;
    private javax.swing.JTextField CNICTF;
    private javax.swing.JTextField DateOfBirthTF;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JButton Employees;
    private javax.swing.JTextField FacilitiesTF;
    private javax.swing.JTextField FatherNameTF;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JTextField LastNameTF;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JTextField ProgramTF;
    private javax.swing.JLabel Register2Button;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RoomTF;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JTextField StudentIDTF;
    private javax.swing.JButton VoucherButton;
    // End of variables declaration//GEN-END:variables
}
