/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class admreg2GUI extends javax.swing.JFrame {

    /**
     * Creates new form admreg2
     */
    public admreg2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        Employees = new javax.swing.JButton();
        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        ShowAvailbleRoomsButton = new javax.swing.JButton();
        RoomNoTF = new javax.swing.JTextField();
        MessRadioButton = new javax.swing.JRadioButton();
        LaundryButton = new javax.swing.JRadioButton();
        ParkingRadioButton = new javax.swing.JRadioButton();
        GymRadioButton = new javax.swing.JRadioButton();
        SingleRoomRadioButton = new javax.swing.JRadioButton();
        admreg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterButton.setBorder(null);
        RegisterButton.setContentAreaFilled(false);
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(20, 90, 140, 30);

        EditButton.setBorder(null);
        EditButton.setContentAreaFilled(false);
        getContentPane().add(EditButton);
        EditButton.setBounds(20, 140, 140, 30);

        RoomsButton.setBorder(null);
        RoomsButton.setContentAreaFilled(false);
        getContentPane().add(RoomsButton);
        RoomsButton.setBounds(20, 190, 140, 30);

        Employees.setBorder(null);
        Employees.setContentAreaFilled(false);
        getContentPane().add(Employees);
        Employees.setBounds(20, 230, 140, 30);

        VoucherButton.setBorder(null);
        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        getContentPane().add(VoucherButton);
        VoucherButton.setBounds(30, 280, 130, 29);

        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(20, 510, 130, 30);

        NextButton.setBorder(null);
        NextButton.setBorderPainted(false);
        NextButton.setContentAreaFilled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton);
        NextButton.setBounds(420, 490, 140, 30);

        ShowAvailbleRoomsButton.setBorder(null);
        ShowAvailbleRoomsButton.setContentAreaFilled(false);
        ShowAvailbleRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAvailbleRoomsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowAvailbleRoomsButton);
        ShowAvailbleRoomsButton.setBounds(590, 200, 170, 30);

        RoomNoTF.setBorder(null);
        RoomNoTF.setOpaque(false);
        RoomNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNoTFActionPerformed(evt);
            }
        });
        getContentPane().add(RoomNoTF);
        RoomNoTF.setBounds(220, 200, 270, 30);

        MessRadioButton.setAlignmentY(0.0F);
        MessRadioButton.setBorder(null);
        MessRadioButton.setIconTextGap(3);
        MessRadioButton.setMargin(new java.awt.Insets(1, 1, 1, 1));
        MessRadioButton.setMaximumSize(new java.awt.Dimension(15, 15));
        MessRadioButton.setMinimumSize(new java.awt.Dimension(15, 15));
        MessRadioButton.setOpaque(false);
        MessRadioButton.setPreferredSize(new java.awt.Dimension(15, 15));
        MessRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MessRadioButton);
        MessRadioButton.setBounds(220, 340, 133, 20);

        LaundryButton.setAlignmentY(0.0F);
        LaundryButton.setBorder(null);
        LaundryButton.setOpaque(false);
        getContentPane().add(LaundryButton);
        LaundryButton.setBounds(220, 361, 70, 30);

        ParkingRadioButton.setAlignmentY(0.0F);
        ParkingRadioButton.setBorder(null);
        ParkingRadioButton.setOpaque(false);
        getContentPane().add(ParkingRadioButton);
        ParkingRadioButton.setBounds(220, 380, 90, 40);

        GymRadioButton.setAlignmentY(0.0F);
        GymRadioButton.setBorder(null);
        GymRadioButton.setOpaque(false);
        getContentPane().add(GymRadioButton);
        GymRadioButton.setBounds(220, 411, 100, 30);

        SingleRoomRadioButton.setAlignmentY(0.0F);
        SingleRoomRadioButton.setBorder(null);
        SingleRoomRadioButton.setOpaque(false);
        getContentPane().add(SingleRoomRadioButton);
        SingleRoomRadioButton.setBounds(220, 440, 21, 21);

        admreg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amdin_registernew2.jpg"))); // NOI18N
        getContentPane().add(admreg2);
        admreg2.setBounds(0, 0, 800, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextButtonActionPerformed

    private void ShowAvailbleRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAvailbleRoomsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowAvailbleRoomsButtonActionPerformed

    private void RoomNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNoTFActionPerformed

    private void MessRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admreg2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admreg2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admreg2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admreg2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admreg2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JButton Employees;
    private javax.swing.JRadioButton GymRadioButton;
    private javax.swing.JRadioButton LaundryButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JRadioButton MessRadioButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JRadioButton ParkingRadioButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RoomNoTF;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JButton ShowAvailbleRoomsButton;
    private javax.swing.JRadioButton SingleRoomRadioButton;
    private javax.swing.JButton VoucherButton;
    private javax.swing.JLabel admreg2;
    // End of variables declaration//GEN-END:variables
}
