
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class admreg3GUI extends javax.swing.JFrame {

    /**
     * Creates new form admreg3
     */
    int std_id;

    admin_driverCode adm_dc = new admin_driverCode();
    student_driverCode std_dc = new student_driverCode();

    public admreg3GUI() {
        initComponents();
        setResizable(false);
        setSize(810, 600);

    }

    public admreg3GUI(int id) throws SQLException {

        std_id = id;
        initComponents();
        setResizable(false);
        setSize(810, 600);

        std_dc.showProfile(std_id);
        FirstNameTF.setText(std_dc.profile.get(0));
        LastNameTF.setText(std_dc.profile.get(1));
        FatherNameTF.setText(std_dc.profile.get(2));
        CNICTF.setText(std_dc.profile.get(3));
        ProgramTF.setText(std_dc.profile.get(4));
        DateOfBirthTF.setText(std_dc.profile.get(5));
        AddressTF.setText(std_dc.profile.get(6));
        PhoneTF.setText(std_dc.profile.get(7));
        EmailTF.setText(std_dc.profile.get(8));
        RoomTF.setText(std_dc.profile.get(9));
        StudentIDTF.setText(std_dc.profile.get(10));
        BuildingTF.setText(std_dc.profile.get(11));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        Employees = new javax.swing.JButton();
        FirstNameTF = new javax.swing.JTextField();
        StudentIDTF = new javax.swing.JTextField();
        FatherNameTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        DateOfBirthTF = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        RoomTF = new javax.swing.JTextField();
        FacilitiesTF = new javax.swing.JTextField();
        LastNameTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        ProgramTF = new javax.swing.JTextField();
        CNICTF = new javax.swing.JTextField();
        BuildingTF = new javax.swing.JTextField();
        NextButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Register2Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        VoucherButton.setBorder(null);
        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        VoucherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoucherButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VoucherButton);
        VoucherButton.setBounds(30, 280, 130, 29);

        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(20, 510, 130, 30);

        RegisterButton.setBorder(null);
        RegisterButton.setContentAreaFilled(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(20, 90, 140, 30);

        EditButton.setBorder(null);
        EditButton.setContentAreaFilled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton);
        EditButton.setBounds(20, 140, 140, 30);

        RoomsButton.setBorder(null);
        RoomsButton.setContentAreaFilled(false);
        RoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RoomsButton);
        RoomsButton.setBounds(20, 190, 140, 30);

        Employees.setBorder(null);
        Employees.setContentAreaFilled(false);
        Employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(Employees);
        Employees.setBounds(20, 230, 140, 30);

        FirstNameTF.setEditable(false);
        FirstNameTF.setBorder(null);
        FirstNameTF.setOpaque(false);
        getContentPane().add(FirstNameTF);
        FirstNameTF.setBounds(320, 200, 170, 20);

        StudentIDTF.setEditable(false);
        StudentIDTF.setBorder(null);
        StudentIDTF.setOpaque(false);
        getContentPane().add(StudentIDTF);
        StudentIDTF.setBounds(320, 220, 440, 14);

        FatherNameTF.setEditable(false);
        FatherNameTF.setBorder(null);
        FatherNameTF.setOpaque(false);
        getContentPane().add(FatherNameTF);
        FatherNameTF.setBounds(320, 250, 160, 14);

        PhoneTF.setEditable(false);
        PhoneTF.setBorder(null);
        PhoneTF.setOpaque(false);
        getContentPane().add(PhoneTF);
        PhoneTF.setBounds(320, 276, 160, 20);

        DateOfBirthTF.setEditable(false);
        DateOfBirthTF.setBorder(null);
        DateOfBirthTF.setOpaque(false);
        getContentPane().add(DateOfBirthTF);
        DateOfBirthTF.setBounds(320, 300, 160, 14);

        AddressTF.setEditable(false);
        AddressTF.setBorder(null);
        AddressTF.setOpaque(false);
        getContentPane().add(AddressTF);
        AddressTF.setBounds(320, 330, 440, 20);

        RoomTF.setEditable(false);
        RoomTF.setBorder(null);
        RoomTF.setOpaque(false);
        getContentPane().add(RoomTF);
        RoomTF.setBounds(320, 356, 170, 14);

        FacilitiesTF.setEditable(false);
        FacilitiesTF.setBorder(null);
        FacilitiesTF.setOpaque(false);
        getContentPane().add(FacilitiesTF);
        FacilitiesTF.setBounds(320, 380, 430, 14);

        LastNameTF.setEditable(false);
        LastNameTF.setBorder(null);
        LastNameTF.setOpaque(false);
        LastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(LastNameTF);
        LastNameTF.setBounds(580, 200, 180, 14);

        EmailTF.setEditable(false);
        EmailTF.setBorder(null);
        EmailTF.setOpaque(false);
        getContentPane().add(EmailTF);
        EmailTF.setBounds(580, 250, 180, 20);

        ProgramTF.setEditable(false);
        ProgramTF.setBorder(null);
        ProgramTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramTFActionPerformed(evt);
            }
        });
        getContentPane().add(ProgramTF);
        ProgramTF.setBounds(580, 273, 190, 20);

        CNICTF.setEditable(false);
        CNICTF.setBorder(null);
        CNICTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNICTFActionPerformed(evt);
            }
        });
        getContentPane().add(CNICTF);
        CNICTF.setBounds(580, 300, 170, 20);

        BuildingTF.setEditable(false);
        BuildingTF.setBorder(null);
        BuildingTF.setOpaque(false);
        BuildingTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingTFActionPerformed(evt);
            }
        });
        getContentPane().add(BuildingTF);
        BuildingTF.setBounds(580, 350, 180, 20);

        NextButton.setBorder(null);
        NextButton.setBorderPainted(false);
        NextButton.setContentAreaFilled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton);
        NextButton.setBounds(420, 490, 140, 30);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(620, 480, 110, 23);

        Register2Button.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Register2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amdin_registernew3.jpg"))); // NOI18N
        Register2Button.setOpaque(true);
        getContentPane().add(Register2Button);
        Register2Button.setBounds(0, 0, 800, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        setVisible(false);
        adminwelcomeGUI a = new adminwelcomeGUI();
        a.setVisible(true);
    }//GEN-LAST:event_NextButtonActionPerformed

    private void CNICTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNICTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNICTFActionPerformed

    private void ProgramTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramTFActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        setVisible(false);
        adminrg1GUI a = new adminrg1GUI();
        a.setVisible(true);
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        setVisible(false);
        adminedit1GUI a;
        try {
            a = new adminedit1GUI();
            a.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(admreg3GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EditButtonActionPerformed

    private void RoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsButtonActionPerformed
        setVisible(false);
        adminroomsGUI a;
        try {
            a = new adminroomsGUI();
            a.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(admreg3GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_RoomsButtonActionPerformed

    private void EmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeesActionPerformed
        setVisible(false);
        admitempGUI a = new admitempGUI();
        a.setVisible(true);
    }//GEN-LAST:event_EmployeesActionPerformed

    private void VoucherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoucherButtonActionPerformed
        setVisible(false);
        adminvoucherGUI a = new adminvoucherGUI();
        a.setVisible(true);
    }//GEN-LAST:event_VoucherButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        setVisible(false);
        IntialGui a = new IntialGui();
        a.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void BuildingTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildingTFActionPerformed

    private void LastNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTFActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        adminrg1GUI a = new adminrg1GUI();
        a.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admreg3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admreg3GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTF;
    private javax.swing.JTextField BuildingTF;
    private javax.swing.JTextField CNICTF;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DateOfBirthTF;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JButton Employees;
    private javax.swing.JTextField FacilitiesTF;
    private javax.swing.JTextField FatherNameTF;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JTextField LastNameTF;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JTextField ProgramTF;
    private javax.swing.JLabel Register2Button;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RoomTF;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JTextField StudentIDTF;
    private javax.swing.JButton VoucherButton;
    // End of variables declaration//GEN-END:variables
}
