/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class IntialGui extends javax.swing.JFrame {

    /**
     * Creates new form IntialGui
     */
    public IntialGui() {
        initComponents();
        setSize(810,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admloginbutton = new javax.swing.JButton();
        stdloginbutton = new javax.swing.JButton();
        IntialLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 569));
        setMinimumSize(new java.awt.Dimension(800, 569));
        setPreferredSize(new java.awt.Dimension(800, 569));
        setResizable(false);
        getContentPane().setLayout(null);

        admloginbutton.setBorderPainted(false);
        admloginbutton.setContentAreaFilled(false);
        admloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admloginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(admloginbutton);
        admloginbutton.setBounds(470, 310, 240, 50);

        stdloginbutton.setBorderPainted(false);
        stdloginbutton.setContentAreaFilled(false);
        stdloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdloginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(stdloginbutton);
        stdloginbutton.setBounds(470, 240, 240, 50);

        IntialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Initial.jpg"))); // NOI18N
        getContentPane().add(IntialLabel);
        IntialLabel.setBounds(0, 0, 850, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdloginbuttonActionPerformed
        setVisible(false);
        StudentLoginGUI a = new StudentLoginGUI();
        a.setVisible(true);        // TODO add your handling code here:
        System.out.println("I");
    }//GEN-LAST:event_stdloginbuttonActionPerformed

    private void admloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admloginbuttonActionPerformed
       setVisible(false);
        admloginGUI a = new admloginGUI();
        a.setVisible(true);
    }//GEN-LAST:event_admloginbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntialGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntialGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntialGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntialGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntialGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IntialLabel;
    private javax.swing.JButton admloginbutton;
    private javax.swing.JButton stdloginbutton;
    // End of variables declaration//GEN-END:variables
}
