/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur
 */
public class stdpassGUI extends javax.swing.JFrame {

    /**
     * Creates new form stdpassGUI
     */
    public stdpassGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfileButton = new javax.swing.JButton();
        VoucherButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        OldPasswordTF = new javax.swing.JTextField();
        NewPasswordTF = new javax.swing.JTextField();
        ConfirmPasswordTF = new javax.swing.JTextField();
        stdpass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ProfileButton.setBorderPainted(false);
        ProfileButton.setContentAreaFilled(false);
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ProfileButton);
        ProfileButton.setBounds(20, 90, 140, 30);

        VoucherButton.setBorderPainted(false);
        VoucherButton.setContentAreaFilled(false);
        getContentPane().add(VoucherButton);
        VoucherButton.setBounds(20, 140, 130, 29);

        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(20, 510, 130, 30);

        UpdateButton.setBorder(null);
        UpdateButton.setContentAreaFilled(false);
        UpdateButton.setOpaque(false);
        getContentPane().add(UpdateButton);
        UpdateButton.setBounds(420, 390, 150, 29);

        CancelButton.setBorder(null);
        CancelButton.setBorderPainted(false);
        CancelButton.setContentAreaFilled(false);
        CancelButton.setOpaque(false);
        getContentPane().add(CancelButton);
        CancelButton.setBounds(420, 430, 150, 30);

        OldPasswordTF.setBorder(null);
        OldPasswordTF.setOpaque(false);
        OldPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldPasswordTFActionPerformed(evt);
            }
        });
        getContentPane().add(OldPasswordTF);
        OldPasswordTF.setBounds(380, 176, 230, 30);

        NewPasswordTF.setBorder(null);
        NewPasswordTF.setOpaque(false);
        getContentPane().add(NewPasswordTF);
        NewPasswordTF.setBounds(380, 250, 230, 30);

        ConfirmPasswordTF.setBorder(null);
        ConfirmPasswordTF.setOpaque(false);
        getContentPane().add(ConfirmPasswordTF);
        ConfirmPasswordTF.setBounds(380, 320, 230, 40);

        stdpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/std_changepw.jpg"))); // NOI18N
        getContentPane().add(stdpass);
        stdpass.setBounds(0, 0, 800, 569);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void OldPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OldPasswordTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stdpassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stdpassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stdpassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stdpassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stdpassGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField ConfirmPasswordTF;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField NewPasswordTF;
    private javax.swing.JTextField OldPasswordTF;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton VoucherButton;
    private javax.swing.JLabel stdpass;
    // End of variables declaration//GEN-END:variables
}
