
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mayur
 */
public class StudentLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentLoginGUI
     */
//    database db = new database();
    student_driverCode std_dc = new student_driverCode();

    public StudentLoginGUI() {

        initComponents();
        setResizable(false);
        setSize(810, 600);

        //  stdloginTF.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stdloginTF = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        stdpwTF = new javax.swing.JPasswordField();
        StudentLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        stdloginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdloginTFActionPerformed(evt);
            }
        });
        getContentPane().add(stdloginTF);
        stdloginTF.setBounds(430, 260, 250, 40);

        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(530, 390, 140, 40);

        stdpwTF.setMargin(new java.awt.Insets(2, 2, 1, 1));
        stdpwTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdpwTFActionPerformed(evt);
            }
        });
        getContentPane().add(stdpwTF);
        stdpwTF.setBounds(430, 330, 250, 40);

        StudentLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/std_login.jpg"))); // NOI18N
        getContentPane().add(StudentLogin);
        StudentLogin.setBounds(0, 0, 870, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        setVisible(false);

        String pwd = new String(stdpwTF.getPassword());
        int id = Integer.parseInt(stdloginTF.getText());
        try {
            std_dc.stdLogin(id, pwd);

        } catch (SQLException ex) {
            Logger.getLogger(StudentLoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void stdloginTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdloginTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdloginTFActionPerformed

    private void stdpwTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdpwTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdpwTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StudentLogin;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField stdloginTF;
    private javax.swing.JPasswordField stdpwTF;
    // End of variables declaration//GEN-END:variables
}
